### ISSUE TITLE
Greedy cut in openning 

### ISSUE THREAD

**Issue by akrasuski** [aamks/aamks#10]
Increasing the width of doors used for cutting in walls caused the problem of gaps in walls. You forgot that HOLE uses the same schema. Finally when holes cut in walls they make a gap and agents use this gap to escape from building :). See attached screen. 
![zrzut ekranu z 2018-07-12 11-46-52](https://user-images.githubusercontent.com/23481420/42626239-0f4df8ca-85ca-11e8-8834-706690c6a69f.png)

**Comment by mimooh** [comment]
fixed
