### ISSUE TITLE
Reducing speed on stairs

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#103]
To reduce speed on stairs to resultant of horizontal and vertical speeds.

**Comment by AleksanderKamienski** [comment]
fe2e251102aa894566b5ce70c4c9debfbea70265 added in simplified way. Speed reduction on whole stairway surface (even horisontal parts) It can by improved in the future for example by adding in apaitner object of type "flight of stair" and only agents located on this object will have reduced speed.

**Comment by kowalskiw** [comment]
That's it for now, to be supported by literature-based values in the future.
