### ISSUE TITLE
Alternative ways to create project/scenario

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#104]
1. Duplicating scenarios or projects with all their settings.
2. Uploading/downloading projects with all their settings.

This feature was requested few years ago (#22). To be revisited.

**Comment by kamil0301** [comment]
Ability to copy scenarios within a project added in #160

**Comment by kowalskiw** [comment]
Resolved in https://github.com/aamks/aamks/commit/e15cc85586d088103cf1b42f785e13f717a9a675
