### ISSUE TITLE
Agents anomalies

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#119]
There were some anomalies observed on animations. I am not sure if this is problem with animation or evacuation itself.

1. Agents have anomalous goals after being teleported to the lower level (somehow perpendicular to supposed direction of the flow).
2. Agents do not move, although some of them has vectors assigned.

Source simulations to be find at my account (proj: "rescue", sim: "off", iteration: many, but for example 105).

![image](https://github.com/aamks/aamks/assets/27781986/31181e85-a477-4044-9f95-841b7e552a7d)

@AleksanderKamienski - could you take a look on this issue?

**Comment by AleksanderKamienski** [comment]
building exit doors were not visble, fixed in 96f31568c6c7ed5cf2cbc4dfdccf78dd6c52c5eb

**Comment by AleksanderKamienski** [comment]
building exit doors were not visble, fixed in 96f31568c6c7ed5cf2cbc4dfdccf78dd6c52c5eb
