### ISSUE TITLE
Evacuee button not visible

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#136]
Evacuee button not activated:
<img src="https://github.com/aamks/aamks/assets/27781986/7335b867-f2d7-43ab-89b2-d796e556c0e8" width=450>

Button activated:
<img src="https://github.com/aamks/aamks/assets/27781986/cc4a15bc-bf7a-4413-962e-c5122dd412fe" width=400>

**Comment by mmackiewicz97** [comment]
EVACUEE has broken color hex in inc.json, change color evacuee or floor_teleport may be consider
