### ISSUE TITLE
test aamks by creating geometries where the floors have different heights

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#154]
Test aamks by creating geometries where the floors have different heights. Maybe there will be some bugs.

**Comment by kowalskiw** [comment]
It seems there are no more bugs than this you spotted in `montecarlo.cfast_mcarlo`. I did some tests (see foo/pietra_rozne on my profile) and CFAST geometry was fine.
However, we can consider adjusting speed on staircases to reflect level difference between subsequent floors. The higher the difference the lower speed on stairwell should be, am I right?
