### ISSUE TITLE
sort and fix animator simulations list

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#155]
Animator simulations list should by ordered by date of creation animation. Another thing is the display of simulations that did not calculate well for some reasons and cannot be viewed. after pressing "Go to anim" there is a message "Aamks is halting on error:
Empty or broken json /home/aamks_users/xxx@mail.com/xx/xx/workers/anims.json". These are the animations that do not have numbers in some columns:

![image](https://github.com/aamks/aamks/assets/33099769/a828f7f6-ff18-4f17-acd4-af396bee75c8)

**Comment by kowalskiw** [comment]
I'm sure that @mmackiewicz97 already introduced those changes on relevant branch.

**Comment by mmackiewicz97** [comment]
Resolve in #79 issue
