### ISSUE TITLE
Issues with charts in the summary and comparisons (simulation.php, new_beck.py, installer) 

### ISSUE THREAD

**Issue by kamil0301** [aamks/aamks#177]
### Installer
Right now in the installer is missing the SALib python package and pandas packge installed will not generate charts (pandas 2.1.1 will not work, pandas 1.5.3 works, this can be an issue with the version of this package or one of its' dependencies).

### Chart generation
  Now comparison charts are created in _comp folder in a project every time the user want to view the charts. I think a table should be added to view already made charts for the comparisons with an option to recalculate the charts. 
**EDIT**: This is expected behavior, to ensure that all calculated simulations are included in the charts

Also with the option to rename scenarios and projects (#166) added, chart folders should be named after id of the simulations instead of name to make location independent of the names of the scenarios. 
**EDIT**: As the charts are calculated each time, this is not really needed.

When making the comparison of two scenarios and postprocess was not done on one of them, data in the tables are missing (risk indices, multisimulation output). Maybe when a comparison is run, independent post-process should also be run for all the scenarios in the comparison to update the data. I need to test this further.

**Comment by kowalskiw** [comment]
resolved with using python 3.10 in venv as default (https://github.com/aamks/aamks/commit/9afe0434712e273ab6503bb1d8a8dea6e6183997)
