### ISSUE TITLE
_next_room_in_smoke function in rvo2_dto.py not working properly

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#187]
The function checks whether the room in which the path[1] coordinate is located has an optical density of smoke higher than the room in which the agent is located. Sometimes it happens that both rooms are the same. the algorithm should be improved so that it checks the next room (which for example may contain the point path[3] because path[1] and path[2] are in the same room as agent). Additionally, the condition should be checked whether hgt > self.config['LAYER_HEIGHT'] and the optical dencity of the hot or cold layer should be chosen accordingly.

**Comment by kowalskiw** [comment]
resolved since https://github.com/aamks/aamks/commit/8b34fa1814fb352d2f0ae3648c4b0adc64ff86c7
