### ISSUE TITLE
Apainter: x-coordinates inconsistent

### ISSUE THREAD

**Issue by shostikk** [aamks/aamks#20]
Display and info text x-coordinates of a room are inconsistent. See enclosed image

![aamks_coord-x](https://user-images.githubusercontent.com/12714528/65660480-8888ca80-e037-11e9-8e71-c16c37ff6847.png)

**Comment by mimooh** [comment]
Could you specify what exactly you mean? Anyway, there's a newer version of Aamks in the development with a different coordinates handling.

**Comment by shostikk** [comment]
Sorry, I was confused (again) by the units (cm), which is a bit unconventional choice. I was thinkin in m (which would be more logical, in my opinion :-)

Can close this
