### ISSUE TITLE
Increase number of statuses logged to psql

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#203]
In order to evaluate simulation progress for complex scenarios we should implement additional checkpoints when status is logged to psql. Examples:

* job received by worker (popped from queue)
* CFAST simulation started
* CFAST simulation finished

Moreover, errors at all possible stages should be caught and saved as status error (1-99).

**Comment by kowalskiw** [comment]
In progress statuses should be greater than 1000. Any lower status results in error sent to psql and crash in sim.

**Comment by mmackiewicz97** [comment]
resolved in worker-logs
