### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by shostikk** [aamks/aamks#22]
Just to document the features we discussed this week:
0) Identify test runs (1 simulation) and give higher priority.
1) Project / scenario copy-to-new (avoid using text saves and typing)
2) Project / scenario download / upload
3) Scenario reset = remove previous calculations from the database
4) Button for stopping the calculation (this is big task with Gearman)
5) Scenario 'Submit' could be just 'Save'
6) Indication that the job is running. Now students press 'Launch' again when they think that they failed to start the simulation.
7) Simulation results database download (.csv)
8) Event tree FED branch logic revisiting. No suggestion yet.
9) Animator should default to the latest finalized simulation, not OnEnd()
10) Scenario setup parameters could be grouped under sub-headings (General, Safety systems, Evacuation, Fire)
11) Move indoor temperature and humidiy under 'Advanced' inputs.

**Comment by mimooh** [comment]
Thanks. Adding to my todo list. At least some are easy to fix.

**Comment by mimooh** [comment]
Reverting to open
