### ISSUE TITLE
Bad fire definition in cfast.in

### ISSUE THREAD

**Issue by akrasuski** [aamks/aamks#23]
Cfast does not work in cm. It requires meters. Problem with cm I can fix myself, however, in the fire definition, the absolute coordinates were used instead of relative to the room of fire origin. 

!! FIRE,compa,x,y,z,fire_number,ignition_type,ignition_criterion,ignition_target,?,?,name
FIRE,1,79700,153000,5000,1,TIME,0,0,0,0,medium

**Comment by akrasuski** [comment]
examplary cfast.in from simple project.

**Comment by mimooh** [comment]
Should be now fixed. We need to keep two representations: one is for CFAST (metres, relative), one is for visualizations (cm, absolute). But obviously we need to handle them properly and it was a bug.
