### ISSUE TITLE
cfast often freezes in one case

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#234]
in building geometry given below cfast freezes very often

[cad.json](https://github.com/aamks/aamks/files/13919333/cad.json)

**Comment by kowalskiw** [comment]
I've investigated the cases you sent to me directly. It seems that for some reason intel-compiled version wasn't able to finish most of them. However, we have mechanism implemented that in case of CFAST timeout or error fire simulation is restarted in GNU-compiled program. GNU calculated all of them.

Switch to GNU as our first choice should be considered or at least implementation of option for user/admin to choose the version. Those should be in form or global `evac/config.json` respectively. Decision promoting Intel-compiled version was based on previous experience of akrasuski's team.

**Comment by kowalskiw** [comment]
If the issue will occur more frequent the switch of default CFAST compilation to GNU should be considered. Closing as not planned at the moment.

**Comment by kowalskiw** [comment]
If the issue will occur more frequent the switch of default CFAST compilation to GNU should be considered. Closing as not planned at the moment.
