### ISSUE TITLE
apainter problems

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#244]
There is a problem with apainter in the case of large buildings (with many floors and compartments). Sometimes you cannot save changes and the program hangs. Example below:
If you want to delete rooms 45, 46, 47 from 1st floor and then draw one room in their place and click the "save" button, the building geometry is not saved to cad.json and the program hangs:
![rooms](https://github.com/aamks/aamks/assets/33099769/f3cab952-25c0-438b-9b23-a40736b6e3e6)

![rooms2](https://github.com/aamks/aamks/assets/33099769/813394da-458e-4488-aae4-fa8befb137b7)

cad.json for this case:
[cad.json](https://github.com/aamks/aamks/files/14069393/cad.json)

Additionally, sometimes it happens that two doors appear in place of a door when you try to delete door with 'x' key. Sometimes when you delete room or door with 'x' key it does not disappear from 2d apainter view even though it is no longer listed on the right. Only by clicking the save button and refreshing the page does the object disappear from the appinter 2D view. Sometimes the CAD drawing support function does not work properly and you cannot draw a hole from wall to wall because it moves to another parallel plane.

**Comment by kowalskiw** [comment]
Maybe this is because of HOLE entity not being attached to compartment boundary anymore? This is a mistake and should not be accepted by Apainter as valid geometry and saved.

**Comment by mmackiewicz97** [comment]
In this case is because of snapping, r201 overlapping r42 room, double line is visible. If you start drawing room in right top corner of r42 to r41, there is no problem.
