### ISSUE TITLE
php preg_replace() error when there is no underlay plane for copied floor

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#247]
[Wed Jan 24 09:37:34.715086 2024] [php:notice] [pid 8196] [client ::1:41944] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /usr/local/aamks/gui/ajax.php on line 44, referer: http://localhost/aamks/apainter/index.php
[Wed Jan 24 09:37:34.715109 2024] [php:notice] [pid 8196] [client ::1:41944] PHP Stack trace:, referer: http://localhost/aamks/apainter/index.php
[Wed Jan 24 09:37:34.715114 2024] [php:notice] [pid 8196] [client ::1:41944] PHP   1. {main}() /usr/local/aamks/gui/ajax.php:0, referer: http://localhost/aamks/apainter/index.php
[Wed Jan 24 09:37:34.715118 2024] [php:notice] [pid 8196] [client ::1:41944] PHP   2. main() /usr/local/aamks/gui/ajax.php:321, referer: http://localhost/aamks/apainter/index.php
[Wed Jan 24 09:37:34.715122 2024] [php:notice] [pid 8196] [client ::1:41944] PHP   3. ajaxGetUnderlay() /usr/local/aamks/gui/ajax.php:313, referer: http://localhost/aamks/apainter/index.php
[Wed Jan 24 09:37:34.715128 2024] [php:notice] [pid 8196] [client ::1:41944] PHP   4. preg_replace($pattern = '/#/', $replacement = '%23', $subject = NULL) /usr/local/aamks/gui/ajax.php:44, referer: http://localhost/aamks/apainter/index.php
[Wed Jan 24 09:37:34.715853 2024] [php:notice] [pid 9460] [client ::1:41984] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(, referer: http://localhost/aamks/apainter/index.php
cat: /home/aamks_users/majster1281@wp.pl/pawel/v9/underlays/8.svg: No such file or directory

**Comment by kowalskiw** [comment]
Not able to be reproduced.
