### ISSUE TITLE
Aamks loses evac_cluster variable

### ISSUE THREAD

**Issue by akrasuski** [aamks/aamks#26]
After updating or just saving the parameters of the project, Aamks loses the evac_cluster variable. It is no more available in conf.json file. 
![Zrzut ekranu z 2019-10-08 14-46-22](https://user-images.githubusercontent.com/23481420/66396990-318dd880-e9db-11e9-8376-ea6558f350b9.png)

**Comment by mimooh** [comment]
Fixed in master
