### ISSUE TITLE
cfast importer and cfast mcarlo problems

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#267]
Building geometry data is modeled incorrectly. The cfast importer loads the geometry from apainter into aamks.sqlite, then, based on the geometric data from aamks.sqlite, cfast_mcarlo creates the cfast.in file where, among other things, it specifies the location of the hole (for example, a door). The problem is that when looking at the building plan from the top in apainter, the coordinates increase going to the right or down and in smokeview, looking from the top at the building plan, the coordinates increase going down and left. Below is an example of a problem where cfast_mcatlo specified FACE = 'LEFT' for hole d3, which caused the geometry of the building in smokeview to be different than in apainter when looking from the top at the building plan, which can be seen in the photos below:
![apainter](https://github.com/aamks/aamks/assets/33099769/cf0ff00b-e65a-4b9d-b9d7-0fbc97b3cbad)
![smokeview](https://github.com/aamks/aamks/assets/33099769/0dc70cc7-2f05-470c-adba-c67d6be992a7)

 cad.json and cfast.in files:

[cad.json](https://github.com/aamks/aamks/files/14871875/cad.json)

[cfast_in.txt](https://github.com/aamks/aamks/files/14871887/cfast_in.txt)

**Comment by kowalskiw** [comment]
To be addressed in the current test series.

**Comment by kowalskiw** [comment]
FACE and OFFSET in CFAST are for visualizing purposes only. This task has very low priority - closing as not planned at the moment.
