### ISSUE TITLE
rvo2 not respecting navmesh?

### ISSUE THREAD

**Issue by mimooh** [aamks/aamks#28]
After m.aamksClearProjects launch navmesh demo. Notice how the evacuees prefer d5 over d6, which is a not what navmesh suggests.

**Comment by akrasuski** [comment]
Is it possible to view animation on szach.in?

**Comment by mimooh** [comment]
> Is it possible to view animation on szach.in?
You can view, but you cannot produce animations. Aamks.szach.in doesn't
have resources to allow visitors to launch RVO2 or CFAST simulations.

-- 
Karol Kreński
tel. 517-302-055

**Comment by akrasuski** [comment]
It is the internal navmesh problem, not the problem that RVO2 does not obey navmesh. I can hardly fix this problem.

**Comment by akrasuski** [comment]
I think we should close issue and place to future request navmesh version 1.5.
