### ISSUE TITLE
Resolve aamks_users locally

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#294]
Some code (`gui.animator.js.animator.loadImage()` as far as was noticed) still use web reference to aamks_users instead of local. All files should be loaded from local sources and hosting aamks_users should be avoided.

**Comment by mmackiewicz97** [comment]
changed in #301

**Comment by kowalskiw** [comment]
Resolved since https://github.com/aamks/aamks/commit/06c71ec20b089506391123ce78ab302f7df4f974

**Comment by kowalskiw** [comment]
There is one more spot where we need `/home/aamks_users` to be hosted - download section of `simulations.php`.

Hosting will probably be unavoidable, however, we should limit the number of files hosted and unauthorised access to them.

This is **privacy issue**.

**Comment by kowalskiw** [comment]
Resolved since https://github.com/aamks/aamks/commit/6d2212820f2925c7983313121ef487d7dd53ce50
