### ISSUE TITLE
levels

### ISSUE THREAD

**Issue by mzimny** [aamks/aamks#3]
In FDS,  I can't add more than 2 extra levels

**Comment by fliszer** [comment]
I need more details, where you can't add extra levels?

**Comment by mzimny** [comment]
I wanted to have 4 layers of gypsum board, but coudn't add extra levels
(layers) in autocad plugin. It works when I add extra ( second or third ...
) level but I have to restart my program to see it.

Do you undarstand now ?

Best regards
Mateusz

Mateusz Zimny
SP-PC15/3

2017-12-03 10:10 GMT+01:00 fliszer <notifications@github.com>:

**Comment by mimooh** [comment]
@fliszer: This issue has been here for almost a year. Either fix or say it won't fix. Why is @mzimny mentioning FDS here in the first place? Aamks doesn't use FDS.

**Comment by mzimny** [comment]
It doesn't matter now. Please, close this topic.

Best Regards

wt., 9 paź 2018, 00:21 użytkownik Karol Kreński <notifications@github.com>
napisał:

**Comment by mimooh** [comment]
Closing on user's request
