### ISSUE TITLE
MVENT room_from

### ISSUE THREAD

**Issue by akrasuski** [aamks/aamks#31]
Information needed in aamks_geom regarding the room where the MVENT is paced. Currently all values related to room are set to None

**Comment by mimooh** [comment]
Fixed in master

**Comment by akrasuski** [comment]
It still needs fixing:
1. is_vertical does not work - get None values
2. offset should be relative to the compartment.
3. Height is tuple in Apainter i.e. 0,50 in database only one value 50. What is first value of the tuple?
