### ISSUE TITLE
Restore HALL functionality

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#323]
HALL was designed to provide connection between compartments on different floors. To be investigated and restored.

Linked to #288 that is more Apainter part of the problem.

**Comment by AleksanderKamienski** [comment]
I will add the logic that only HALL will be able to be used to create rooms with a height higher than the height of the storey. If you try to change the ROOM or COR height to a Z coordinate range other than the defined story height, apainter.js will prevent the change. we will set SHAFT = .TRUE in cfast_mcarlo for a HALL type compartment, there will be a single-zone model as in STAIR

**Comment by kowalskiw** [comment]
Resolved since https://github.com/aamks/aamks/commit/9b774665e0f8d6ab6d9c1dba6e1482618f234df4
