### ISSUE TITLE
Placing virtual compartments into CFAST

### ISSUE THREAD

**Issue by akrasuski** [aamks/aamks#33]
In cfast.in virutal compartments are defined. Is it new problem or I  lost something during migration to CFAST 7.5? 

!! SECTION DOORS AND HOLES
&VENT TYPE = 'WALL', ID = 'd21', COMP_IDS = 'c7', **'s5.1**', WIDTH = 0.9, TOP = 5.5, BOTTOM = 3.5, OFFSET = 22.89, FACE = '1', CRITERION = 'TIME' T = 0 F = 1 /
&VENT TYPE = 'WALL', ID = 'd27', COMP_IDS = 'c9', '**s5.2**', WIDTH = 0.9, TOP = 9.0, BOTTOM = 7.0, OFFSET = 22.88, FACE = '1', CRITERION = 'TIME' T = 0 F = 1 /
&VENT TYPE = 'WALL', ID = 'd25', COMP_IDS = 'c9', 'r10', WIDTH = 0.9, TOP = 2.0, BOTTOM = 0.0, OFFSET = 14.75, FACE = '1', CRITERION = 'TIME' T = 0 F = 1 /
 
 41 !! SECTION NATURAL VENT
&VENT TYPE = 'CEILING', ID = 'b1', COMP_IDS = 'OUTSIDE', '**s1.1**', AREA = 6.0, SHAPE = 'SQUARE', OFFSETS = 3.4, 2.85, CRITERION = 'TIME' T = 0,90 F = 0,0 /
&VENT TYPE = 'CEILING', ID = 'b2', COMP_IDS = 'OUTSIDE', '**s5.2**', AREA = 6.12, SHAPE = 'SQUARE', OFFSETS = 3.62, 5.05, CRITERION = 'TIME' T = 0,90 F = 0,1 /

**Comment by mimooh** [comment]
You need to filter out 's5.1' & friends in your aamks_geom query.
Inspect orig_type or global_type_id.

On 28/04/2020, akrasuski <notifications@github.com> wrote:
> In cfast.in virutal compartments are defined. Is it new problem or I  lost
> something during migration to CFAST 7.5?
>
> !! SECTION DOORS AND HOLES
> &VENT TYPE = 'WALL', ID = 'd21', COMP_IDS = 'c7', **'s5.1**', WIDTH = 0.9,
> TOP = 5.5, BOTTOM = 3.5, OFFSET = 22.89, FACE = '1', CRITERION = 'TIME' T =
> 0 F = 1 /
> &VENT TYPE = 'WALL', ID = 'd27', COMP_IDS = 'c9', '**s5.2**', WIDTH = 0.9,
> TOP = 9.0, BOTTOM = 7.0, OFFSET = 22.88, FACE = '1', CRITERION = 'TIME' T =
> 0 F = 1 /
> &VENT TYPE = 'WALL', ID = 'd25', COMP_IDS = 'c9', 'r10', WIDTH = 0.9, TOP =
> 2.0, BOTTOM = 0.0, OFFSET = 14.75, FACE = '1', CRITERION = 'TIME' T = 0 F =
> 1 /
>
>  41 !! SECTION NATURAL VENT
> &VENT TYPE = 'CEILING', ID = 'b1', COMP_IDS = 'OUTSIDE', '**s1.1**', AREA =
> 6.0, SHAPE = 'SQUARE', OFFSETS = 3.4, 2.85, CRITERION = 'TIME' T = 0,90 F =
> 0,0 /
> &VENT TYPE = 'CEILING', ID = 'b2', COMP_IDS = 'OUTSIDE', '**s5.2**', AREA =
> 6.12, SHAPE = 'SQUARE', OFFSETS = 3.62, 5.05, CRITERION = 'TIME' T = 0,90 F
> = 0,1 /
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/aamks/aamks/issues/33


-- 
Karol Kreński
tel. 517-302-055

**Comment by akrasuski** [comment]
Fixed. File cfast_mcarlo.py function_section_doors_and_holes and _section_vents
