### ISSUE TITLE
Door on upper floor in staircase

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#345]
`geom.cfast_importer._calculate_sills()` does not handle door that are placed on upper floor of multi-tier compartment.

It may be caused by virtual room not saved properly? Probably we should take staircase baseline for `floor_baseline` in that case.

**Comment by AleksanderKamienski** [comment]
will be resolved in #367

**Comment by kowalskiw** [comment]
Resolved since https://github.com/aamks/aamks/commit/9b774665e0f8d6ab6d9c1dba6e1482618f234df4
