### ISSUE TITLE
Apainter allows drawing on negative coordinates

### ISSUE THREAD

**Issue by criitamaa** [aamks/aamks#37]
Apainter allows elements to be drawn in negative coordinates, which then passes negative compartment position values to CFAST, causing errors (CFAST does not allow negative position values)

Wrong value of heat of combustion is passed to CFAST; the value specified in the Aamks simulation parameters by default is a continuous distribution between 16400 and 27000 (kJ/kg) but the value in the cfast.in files is 1/1000 of the value specified i.e. between 16.4 and 27

Attached are two input files with wrong parameters generated by Aamks.

[sim2_cfast.txt](https://github.com/aamks/aamks/files/5379145/sim2_cfast.txt)
[sim9_cfast.txt](https://github.com/aamks/aamks/files/5379147/sim9_cfast.txt)

**Comment by mimooh** [comment]
Can't fix anytime soon. For now you just need to stick to the positive part
of the plane.

śr., 14 paź 2020, 17:01 użytkownik criitamaa <notifications@github.com>
napisał:

**Comment by kowalskiw** [comment]
Let me revive this ancient issue :)
1. Heat of combustion bug has been already fixed on `dev` branch. I'm editing title of the issue.
2.  Apainter improvements has a lower priority now. We will introduce an exception or limitation but probably not in the next version. For the present an adequate note will be added to Wiki page related to drawing geometry.

**Comment by kowalskiw** [comment]
Resolved since https://github.com/aamks/aamks/commit/0c7ef41a622c6f018f72c0f0315c82e55d55aa49.
