### ISSUE TITLE
Removing a project while simulations are running locks user out of account

### ISSUE THREAD

**Issue by criitamaa** [aamks/aamks#38]
Two students reported the described problem: if they launched simulations, but did not wait for all simulations to finish (or end by other means) before deleting the project, they were unable to access their Aamks account on the server after logging out. One student tried to reset their password , but it did not work.

The reason for deleting the project after launching the simulations is that the students erroneously believed the simulations to have crashed, while the simulations were actually either stuck or simply took a long time to finish.

As an interim solution, I advised students to not delete any projects after launching simulations, unless I had restarted Gearman first and terminated all jobs on the workers.

**Comment by kowalskiw** [comment]
Issue is still relevant, despite significant changes in networking and job queuing were made. To be addressed in the future.

**Comment by kowalskiw** [comment]
Resolved since https://github.com/aamks/aamks/commit/732c591771403ad4818cd6a4d00d5465e008b1e8
