### ISSUE TITLE
Cfast freezes

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#45]
Cfast freezes. As a result, the simulations do not run and, for example, when I set the number of simulations to 50 simulations, Aamks will stop at, say, the tenth simulation. This makes it difficult to perform a large number of simulations, because, for example, with 160 simulations done, I have 260 empty ones (they didn't run because of CFASTA suspension).

**Comment by kowalskiw** [comment]
According to @akrasuski this issue is related to CFAST compilation. Compiling CFAST with Intel tool will probably resolve this issue.

Duplicate of issue #42.

**Comment by kowalskiw** [comment]
On the branch `dev` the cfast is compiled with Intel tool (see #42). It should not be freezing anymore. To be observed and if bug still exists this issue will be reopened.
