### ISSUE TITLE
Index out of range rvo2dto.py

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#47]
Index out of range problem in rvo2dto.py file. It appeared in random simulations and it happened when I added a lot of obstacles in geometry. An empty list was passed to the function and then there was a reference to the index of the first element of the list that was not there. Unfortunately, I do not have a saved line of code in which the program crashed or screenshots showing the problem.

**Comment by mmackiewicz97** [comment]
/usr/local/aamks/evac/rvo2_dto.py", line 98, in _find_closest_exit
    exits = list(zip(*paths))[0]
IndexError: list index out of range

**Comment by mmackiewicz97** [comment]
/usr/local/aamks/evac/rvo2_dto.py", line 98, in _find_closest_exit
    exits = list(zip(*paths))[0]
IndexError: list index out of range

**Comment by kowalskiw** [comment]
Probably related to #43 and #52

**Comment by AleksanderKamienski** [comment]
the commit a50a741 solved the issue
