### ISSUE TITLE
broken matplotlib

### ISSUE THREAD

**Issue by zarooba01** [aamks/aamks#50]
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-pzs4ts9h because the default path (/var/www/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing. Traceback (most recent call last): File "/usr/local/aamks/results/beck.py", line 14, in from ete3 import Tree #, TreeStyle, TextFace ModuleNotFoundError: No module named 'ete3' 

What is the use of the mdoule ete3?

**Comment by kowalskiw** [comment]
It seems like it is not used anymore. Hashing this import produce distributions properly and a huge number of warnings about deprecated `seaborn.distplot()` function. To be tested. Following changes to be implemented in `beck.py`:

- [ ] remove redundant import from `et3` and test
- [ ] update plotting function to `seaborn.displot()`
