### ISSUE TITLE
Recast compilation terminated

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#51]
Calling `bash worker_install.sh -i` results in the following error:
```
In file included from Recast/Detour/Source/DetourNavMesh.cpp:27:
Recast/Detour/Include/DetourAssert.h:35:10: fatal error: boost/python.hpp: No such file or directory
   35 | #include <boost/python.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
mkdir: cannot create directory ‘/home/aamks_users’: File exists
```
I also give a try to launch calculations from GUI. Obviously it finished with missing `recast` module:
```
Aamks is halting on error:
Traceback (most recent call last): File "/usr/local/aamks/aamks.py", line 5, in from manager.init import OnInit, OnEnd File "/usr/local/aamks/manager/init.py", line 16, in from geom.nav import Navmesh File "/usr/local/aamks/geom/nav.py", line 10, in import _recast as dt ModuleNotFoundError: No module named '_recast'
```

That installation was made on Ubuntu 22.04.1 LTS set up on VMware Workstation 16.

**Comment by kowalskiw** [comment]
Probably connected to the #48.

**Comment by zarooba01** [comment]
Try install ibboost-python.
`sudo apt-get install libboost-python-dev`
Check whether instalation has gone correctly 
```
cd /usr/lib/x86_64-linux-gnu 
ls | grep libboost_python 
```
You should see something like this:
libboost_python310.so
libboost_python310.so.1.74.0
Now make the link according to your python version
sudo ln -s libboost_python310.so libboost_python3.so
Run worker install again.

**Comment by kowalskiw** [comment]
Your solution works fine, compilation is completed. What about considering a modification of `worker_install.sh` in order to check for the missing package?

However, after installing worker on the same machine as the server (local mode) the repository clone is located at `/usr/local/aamks/aamks` instead of `/usr/local/aamks`. Is it a correct path for the repo?

**Comment by zarooba01** [comment]
We should take this under consideration. In my opinion it should be fixed to /usr/local/aamks.

**Comment by kowalskiw** [comment]
OK, so let's conclude the discussion with some tasks linked to this issue to be solved:

- [ ] investigation of `libboost-python-dev` installation with `worker_install.sh`
- [ ] change of repo's location to `/usr/local/aamks/` after worker installation

**Comment by kowalskiw** [comment]
@mmackiewicz97 - it seems like those tasks can be resolved with updating server and worker installers, as we discussed. So, I'm assigning you to this issue, feel free to close it when both tasks from previous comment are finished.

**Comment by kowalskiw** [comment]
Fixed with yesterday's commit.
