### ISSUE TITLE
Introduction of pynavmesh

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#52]
Use of this package as navmesh and collision avoidance module should be considered in the future: https://github.com/Tugcga/Path-Finder.

**Comment by mimooh** [comment]
There are two projects of the same author actually, both look very promising:
https://github.com/Tugcga/PyRecastDetour/issues/8
https://github.com/Tugcga/Path-Finder/issues/9

**Comment by mimooh** [comment]
I suggest aamks should use Tugcga/Path-Finder (Tugcga/PyRecastDetour would be more complex):

You can use Python version. It can be installed from pip and does not requires any dependencies. At allows to bake navmesh, search shortest path between two points and even has implementation of the RVO2 - agent collision avoidance algorithm. Python page of the module contains some examples how to use it.

**Comment by mimooh** [comment]
I suggest that one person from aamks team is chosen as a maintainer of navmesh and I can introduce him to what is needed on aamks part (a jitsi meeting). Once navmesh is fixed then we can consider switching to RVO2-python also (currently aamks uses a compiled RVO2 lib which adds complexity to the installer, but is likely to be faster).

**Comment by kowalskiw** [comment]
Related to issue #43.

**Comment by kowalskiw** [comment]
Not to be continued at the moment.

**Comment by kowalskiw** [comment]
Switch to pynavmesh is possible in actual version of staircase module and to be considered. I'm reopening this issue.

**Comment by kowalskiw** [comment]
Pynavmesh already introduced on `dev` along with staircase module.
