### ISSUE TITLE
Alarming time from CFAST 

### ISSUE THREAD

**Issue by zarooba01** [aamks/aamks#59]
How long should the pre-evac time last? Pre-evacuation time is based on two factors here: detection time and alarming time. Detection time should be taken from CFAST. Alarming time should be taken from distribution.

**Comment by kowalskiw** [comment]
Sorry for such a late response. According to PD 7974-6 the following components of RSET can be distinguished:

1. Time of detection (from fire start to detection).
2. Time of transmitting the alarm (from detection to the moment alarm is received).
3. Pre-movement time (users' latency - they're checking if it is not a false alarm, gathering their belongings, asking a friend what's going on etc.).
4. Time of travel (movement time needed for an evacuee to travel egress distance).

So, there are more than two components. Pre-movement time (3rd point above) is log-norm distribution. It depends on i.e. alertness, training level of evacuees, staff presence etc. Take a peek at the standard to find more info.

**Comment by kowalskiw** [comment]
Indeed, detection time is not used in simulation at all.

Detection time should be added in `evac.worker._create_evacuees()` to already drawn pre-evacuation time for each evacuee.

**Comment by kowalskiw** [comment]
Resolved in https://github.com/aamks/aamks/commit/a23efc2a986d4f9d598bcdf49e15f0f2beb9a68f
