### ISSUE TITLE
error that occurs when the user is automatically logged out

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#62]
![image](https://user-images.githubusercontent.com/33099769/227920794-8dd9568d-81a5-429f-a04e-b6cecd82a559.png)

Views in the application should be handled when the user is logged out for various reasons, for example after a long time of not using the application.

**Comment by kowalskiw** [comment]
Resolved in https://github.com/aamks/aamks/commit/d7ac601980d2b7113dc138f7f5f82a99e5c3fce0
