### ISSUE TITLE
 wrong choice of exit path by agents

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#66]
The agents choose to exit through the room on fire, which is pointless since there is a second path available without the fire. The path selection algorithm in rvo2_dto.py (terminal door) should be examined and improved

![MicrosoftTeams-image](https://github.com/aamks/aamks/assets/33099769/4dd7dc16-d06d-4e68-8db3-2ab32199fd0f)

**Comment by kowalskiw** [comment]
Another example of wrong goals set for two groups of agents. Although some of changed their goal few times running to the upper corridor for a while. And suddenly they changed their minds and run to the nearest exit (!).

![Image](https://github.com/aamks/aamks/assets/27781986/1e72fdb6-6ef8-45b2-8b44-b0a8039ab9c1)

**Comment by kowalskiw** [comment]
@AleksanderKamienski - is this issue still relevant considering changes you made in rvo2 and navmesh?

**Comment by kowalskiw** [comment]
Problem still persists in some cases - to be investigated with higher priority.

**Comment by kowalskiw** [comment]
Probably resolved since https://github.com/aamks/aamks/commit/8b34fa1814fb352d2f0ae3648c4b0adc64ff86c7.

To be monitored and reopened if needed.
