### ISSUE TITLE
form parameters overwritten

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#67]
In the simulation parameters form, change the time_1, time_2, time_3, time_4 for Nozzles parameters are overwritten in the advanced tab, in the case of saving the building profile in the easy tab. The situation works both ways. If Nozzles parameters are saved, the building profile parameters are overwritten.

It needs to be checked whether it is bug or not, but probably it is.

**Comment by mmackiewicz97** [comment]
Added button to the form so that the parameters are recalculated when button is clicked
