### ISSUE TITLE
catching important scenarios

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#73]
it would be useful to print after time in a given scenario how many people were killed and seriously injured - this would make it possible to select important scenarios where people were killed or seriously injured from many hundreds or thousands of less important scenarios, as in the picture b
![MicrosoftTeams-image (2)](https://github.com/aamks/aamks/assets/33099769/fd235c54-2541-4d97-888f-09165c328fde)
elow:

**Comment by kowalskiw** [comment]
Should be the vital part of more general issue #79. I am closing this one in order to remove the duplicate.
