### ISSUE TITLE
Replacing fire symbol in Animator with real fire surfaces

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#76]
The area of ​​fire should be shown in the animator in aamks. At the moment there is only a fire symbol which does not reflect the actual fire area. This is important because the fire surface is treated as an object of the obst type in navmesh and rvo (agents cannot pass through it) it may happen that the fire will cut off the only escape route, which is currently not visible in the apainter, but it should be. Currently only the fire symbol is shown there, which is often much smaller than the actual fire area.

**Comment by kowalskiw** [comment]
Agreed - drawing it as a red-filled circle seems reasonable, since this is the way CFAST considers the fire area (see section 6.2 of CFSAT User Guide). If possible we should make its radius time-dependent accordingly to the transient heat release rate of the source.

**Comment by AleksanderKamienski** [comment]
I think we should close this issue because, from what I know, at the moment we are assuming the fire is a 1m x 1m area.

**Comment by kowalskiw** [comment]
Resolved in https://github.com/aamks/aamks/commit/fb17abf6737c51282d72030e6f611563e1a6565e
