### ISSUE TITLE
Wall thickness problem.

### ISSUE THREAD

**Issue by akrasuski** [aamks/aamks#8]
It seems that thick walls cause problem with agent movement. Agents go between two part of a wall and stack. Below some example with an agent stacked between wall parts. 
![zrzut ekranu z 2018-06-29 19-08-42](https://user-images.githubusercontent.com/23481420/42105406-89531852-7bd0-11e8-8f3b-aa21676f801f.png)

**Comment by mimooh** [comment]
Attach the cad.json

**Comment by akrasuski** [comment]
[cad_json.txt](https://github.com/aamks/aamks/files/2154120/cad_json.txt)

**Comment by akrasuski** [comment]
Obstacles are added counterclockwise and problem seems to be solved.
