### ISSUE TITLE
error when there is no corridor object in building

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#83]
Error occurs when the building geometry has no corridor. It seems to me that we should correct this error because it may happen that there is some strange geometry of the building and there is no corridor, only rooms and stairs, but this is something to consider

![image](https://github.com/aamks/aamks/assets/33099769/209f6501-2be6-4293-8592-90bba1cd9756)

**Comment by mmackiewicz97** [comment]
resolved in #078b053
